### ISSUE TITLE
Remove settler injection Overrides for FreshFacials and Orphans?

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [kinggath/WorkshopFramework#100]
Heya,
I'm investigating an issue, and I *think* the problem is that the WSFW is detecting FreshFacials (or Orphans of the Commonwealth), and not running injection.

Both of these mods updated recently, and now include patches that take advantage of the injection framework. I'm assuming that the override you setup is actually preventing these patches from working properly.

**Comment by kinggath** [comment]
Ok great - I'll remove them both from the override list!
