### ISSUE TITLE
Sanctuary Build Limit resetting to 100% on save load

### ISSUE THREAD

**Issue by amanimmortal** [kinggath/WorkshopFramework#115]
As title states. The build limit in Sanctuary is resetting to 100% when loading a save. I have tested 200%, 300% and 400% and it resets back to 100% when loading any save. Not happening on fast travel.
I have rolled back to 2.2.1a and the issue does not occur there.

**Comment by kinggath** [comment]
I'm unable to replicate this using the latest build. Are you using other mods in that test?

**Comment by kinggath** [comment]
Ok - found the issue. This is happening due to a hack I came up with to detect when 3rd party scripts are overwriting the workshop scripts.

This is going to occur one more time for everyone after next patch, and then it won't happen again and won't happen for fresh saves started after next patch.
