### ISSUE TITLE
DoorManager expects WorkshopID, causes errors in player homes

### ISSUE THREAD

**Issue by praecipitator** [kinggath/WorkshopFramework#117]
The DoorManager assumes a WorkshopID is set in it's HandlePlayerEnteredSettlement, in it's usage in bDoorRegistrationInProgress and bDoorRegistrationCompleted. This fails in Home Plate, and other mod-added playerhome-like workshops.

A simple solution would be to return right out of HandlePlayerEnteredSettlement, if no WorkshopID is found.
Alternatively, the workshop in question could be flagged with keywords or AVs, when the registration is in progress or completed. Don't know how to reset it, though, the way it currently happens with the iTimerID_CleanupDoorRegistration atm

**Comment by kinggath** [comment]
Switched to keyword tracking of registration for patch 2.4.2.
