### ISSUE TITLE
WSFW_F4SE Has Property no longer in script

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#124]
Quest WSFW_F4SE has a property WSFW_Main defined on the quest form but is no longer defined in the script
```
warning: Property WSFW_Main on script workshopframework:f4semanager attached to WSFW_F4SE (0B00269C) cannot be initialized because the script no longer contains that property
```
![F4SEManager](https://user-images.githubusercontent.com/77886955/185796599-ac6f0683-f61d-4435-8376-26a789e6b8a9.jpg)

**Comment by kinggath** [comment]
Not sure why that was removed at some point - it's definitely in the script currently!
