### ISSUE TITLE
Workshop Framework still broken

### ISSUE THREAD

**Issue by Cric55** [kinggath/WorkshopFramework#127]
when log in i get message that one or more mod are over writing Workshop Framework and that i can get the fix file
from Workshop Framework on nexus, the Workshop Framework Script Override or us the auto sorter on vortex load up my save and there is the message still so tell me please how to fix this

**Comment by kinggath** [comment]
You would need to set up a rule in Vortex to make sure it is always the last mod loaded. Should be tutorials available for that - I haven't used Vortex in a long time so I don't know the steps.
