### ISSUE TITLE
Enhancement: Replace ALCH with FLST in the PurifiedWater property of WorkshopProductionManager script

### ISSUE THREAD

**Issue by Enesore** [kinggath/WorkshopFramework#128]
By default, the "basic resource consumption" setting allows settlers to only consume two things: everything in the `WSFW_VanillaBuildableCrops` FormID list and Purified Water. The former is very easy to patch for mods that change crop outputs, but the latter requires an override of the `WSFW_ProductionManager` quest record itself, which is far from ideal.

In my example, I need to replace `WaterPurified` with `WaterDirty`, and I would really appreciate being able to do this through a FormID list change. This would also allow the user to expand what's considered to be a basic water resource - for example, making both purified and dirty water eligible for consumption.

**Comment by kinggath** [comment]
The default setting actually makes purified and dirty water eligible, as it consumes on ObjectTypeWater which both have. I do like the idea of it being customizable though - maybe someone wants to Idiocracy it up and offer Gatorade haha. Will queue up the change for a patch soon.

**Comment by Enesore** [comment]
It appears as though the FLST for water is present, but is unused by the production manager, which still uses the Purified Water item directly.

**Comment by kinggath** [comment]
Had to hotfix because of the missing header flag, so I fixed this as well while I was at it!
