### ISSUE TITLE
AlwaysAllowedActorTypes property issue

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#136]
In `WSFW_Thread_ExportObjectData` script properties, `AlwaysAllowedActorTypes` 
2226 (0x8B2) in `DLCWorkshop02.esm` does not exist. I assume this was supposed to be the armor racks
`DLC05WorkshopArmorRackMale01` 0x8AC and
`DLC05WorkshopArmorRackFemale01` 0x8B3
Is there a reason this object has a const property instead of having `SettlementLayoutManager.ExportLinkedItems` set it? Then you would only have to maintain one property on the quest.

`WSFW_SettlementLayoutManager` property `AlwaysAllowedActorTypes` has the same issue as above.
In addition the keywords:
`LinkTerminalTurret`
`WorkshopIcon_TurretBubble`
`WorkshopIcon_TurretTripod`
`WorkshopIcon_TurretTripodMounted`
are all defined. Is there some use for these I'm missing? All turrets should have `ActorTypeTurret` assigned by Race.

There is a report that `WorkshopTurretSpotlight` and `DLC01_WorkshopTurretSpotlight` fails to properly  import unless the setting allow actors = true
https://www.simsettlements.com/site/index.php?threads/spotlight-not-included-in-layout-wsfw-imports.19503/
Looking at `WorkshopFramework:Weapons:SettlementLayout.PlaceObjects` the code is checking the object to place against `AlwaysAllowedActorTypes` defined in `WSFW_SettlementLayoutManager` which includes `ActorTypeTurret`. The spotlight objects should have that keyword assigned by Race. Maybe a mod conflict? Maybe I read the code wrong?

**Comment by kinggath** [comment]
8B2 is actually the DLC05ArmorRackKeyword. 

The const properties on the threads are just more efficient. Always better to have the threads do the work themselves when possible - any time two objects talk to each other, there are latent calls which can slow down the code.

So the reason for those other keywords is that we are testing the base forms, not references when determining if we should place an item. The Race inheritence of ActorTypeTurret keyword only happens on references.

So to fix the spotlight, we need to add a keyword on that form to the SettlementLayoutManager AlwaysAllowedActorTypes. I'll get something added for next patch.
