### ISSUE TITLE
water ?

### ISSUE THREAD

**Issue by anvilknight** [kinggath/WorkshopFramework#143]
hey i think you have a bug with your mod (clean save used only your mod) water purifier resource drops gets bugged only removed your mod it's now fixed. the bug is when i wait 24 northing wait or at most 15 purified water even with 800 water (some times it doesn't drop period)

**Comment by kinggath** [comment]
It's actually a bug in Bethesda's code that I fixed. They have a limiter to prevent this sort of economy breaking amount of food and water from being created and then they proceed to break it at another point in their code.
