### ISSUE TITLE
Changing The Workshop's Spawned NPCs

### ISSUE THREAD

**Issue by FiftyTifty** [kinggath/WorkshopFramework#144]
Edit: Lmao there is a wiki, I'm just passive aggressive and blind. My bad.

So by the looks of it, I just need to edit **WSFW_InjectionDefaults_Settler**, **WSFW_InjectionDefaults_SettlerGuard**, **WSFW_InjectionAdditions_Settler**, and **WSFW_InjectionAdditions_SettlerGuard**?

I have created a mod that changes the appearance of the workshop NPCs. This works fine in vanilla, but with Workshop Framework, the way it spawns NPCs is very odd. And I need some clarification.

Unfortunately, there are no docs for working with the API. So I've had to look around and guess what is happening here.

In vanilla, you are able to change the default settler actor spawns by changing the Traits Template for the **WorkshopNPC**, **WorkshopNPCGuard**, **WorkshopNPCFemale**, and **WorkshopNPCMale** Actor records. Simple and easy.

But Workshop Framework doesn't use the vanilla actors, as my changes don't apply. From what I can tell, there are dummy actors that are changed through code. **WSFW_WorkshopNPC** Has templates that point to **WSFW_LCharWorkshopNPC_Holder**. Which are empty lists with no entries in them.

How to modify this, is not documented anywhere. This doesn't make much sense, I assume the levelled lists are appended to by some script somewhere, which is not great. As there are no docs explaining any of this.

How do I replace the settler's faces, with my own actors'?

**Comment by kinggath** [comment]
If you are making changes at the top level, WorkshopNPC and WorkshopNPCGuard, you could make those same changes to the WSFW_WorkshopNPC and WSFW_WorkshopNPCGuard and just release it as a patch.

WorkshopNPCFemale/WorkshopNPCMale shouldn't be impacted by WSFW - those are used by the Random Encounter system which WSFW doesn't hook into.

**Comment by FiftyTifty** [comment]
> If you are making changes at the top level, WorkshopNPC and WorkshopNPCGuard, you could make those same changes to the WSFW_WorkshopNPC and WSFW_WorkshopNPCGuard and just release it as a patch.
> 
> WorkshopNPCFemale/WorkshopNPCMale shouldn't be impacted by WSFW - those are used by the Random Encounter system which WSFW doesn't hook into.

Sorry for not getting back all this time. Life has been real busy.

Aye what I'm doing is just creating more faces for the spawned NPC to pull from. I'll give that a go. Are the injection actors used for anything?
