### ISSUE TITLE
Possible bug: deadlock with RelinkWorkshopActors / GetWorkshopActors

### ISSUE THREAD

**Issue by VerumRex** [kinggath/WorkshopFramework#147]
> It looks like one of the WSFW menu tools ("relink settlers") could be causing a deadlock that's preventing daily updates from working. for me this means that happiness is stuck and not updating. here's the forum link: https://simsettlements.com/site/index.php?threads/possible-bug-deadlock-with-relinkworkshopactors-getworkshopactors.26316/ 
> 
> I added some links to the source code and screenshots from FallrimTools to help identify the problem
it looks like kind of a nasty bug so I'd love to get some eyes on it
> 
> anyway I just tried using a console command to call a function on the stuck script instance. I can update the state using `goToState` and the clear the blocked script instances. This seems to fix the stuck happiness problems, and causes the happiness reports to reflect accurate numbers again

**Comment by weefbellington** [comment]
hi there, I'm the author of the bug report.

I put up a draft PR to fix the issue: https://github.com/kinggath/WorkshopFramework/pull/148

I'll need some guidance on how to patch in the issue for users who are already in a deadlocked state. Basically if the `WorkshopScript` is stuck in the `RelinkingActors` state, we need to change it back to `Initialized`. For example I can fix the issue using a console command:

`<script id>.cf "GoToState" "Initialized"`

I assume there's a callback for running patch code when the framework version is updated, but I'm not sure where that is.

**Comment by kinggath** [comment]
Hotfixed this - should be good to go!
