### ISSUE TITLE
Increasing settlement build limit with "Manage" option always causes WorkshopCurrentTriangles and WorkshopCurrentDraws to be maxed out

### ISSUE THREAD

**Issue by littlej541** [kinggath/WorkshopFramework#155]
https://github.com/kinggath/WorkshopFramework/blob/2c0df8be9642ada18bed2729ceb438366a10ff65/Scripts/Source/User/WorkshopFramework/MainQuest.psc#L609-L611

These are the offending lines. These set the current draws and current triangles to the max draws and max triangles, respectively. This will cause it to always max out the build limit even if you cancel out of the menu.

I'm not sure what these lines were trying to achieve; was it really trying to set the current draws and triangles? Or was it trying to set the max draws and triangles? In either case, I'd say this is a rather big and very annoying issue, especially for those who can't use console commands to the fix problem.

**Comment by kinggath** [comment]
That looks like a strange typo someone made - I'm guessing they were trying to do curDraws, not curMaxDraws. Will take a look at it now while I'm in the process of patching - thanks for the heads up!

**Comment by kinggath** [comment]
Hotfixing now!
