### ISSUE TITLE
Code changes from Github not actually included in Nexus version

### ISSUE THREAD

**Issue by praecipitator** [kinggath/WorkshopFramework#157]
I noticed it with this commit:
https://github.com/kinggath/WorkshopFramework/commit/2c0df8be9642ada18bed2729ceb438366a10ff65
Decompiling `workshopparentscript.pex` shows me that the addition "; WSFW 2.3.16 - Added keyword to prevent registration as a standard settlement" is not actually included, neither in 2.3.16, nor in .17, nor in .18.

**Comment by kinggath** [comment]
Hotfixed!
