### ISSUE TITLE
DLL files on Nexus for NG update are the same files for Old-Gen v2.4.1a

### ISSUE THREAD

**Issue by Blad3K1ll3r** [kinggath/WorkshopFramework#165]
DLL files on Nexus for NG update are the same files for Old-Gen

**Comment by Blad3K1ll3r** [comment]
![image](https://github.com/user-attachments/assets/40932c4b-5ecb-4328-974d-cf56c11c0176)

**Comment by wxMichael** [comment]
@kinggath Just an fyi, this wasn't fixed with 2.4.1b. PowerGridTools.dll last modified date is 4/19/2022.
