### ISSUE TITLE
The WSFW production manager quest does not use the vanilla leveled list of vendor income

### ISSUE THREAD

**Issue by redbaron148** [kinggath/WorkshopFramework#32]
XX007AFB - WSFW_ProductionManager, WSFW's production management quest script, has caps coded in the quest script's parameters.

Changing this to point at the vanilla leveled list (0010C846 - WorskhopProduceVendorIncome) would improve WSFW's goal of transparency with other mods (Horizon).  Any mod could change that one vanilla leveled list to change income and not be required to override WSFW's quest script.

I had already reported this on discord, but I figured it would be easier to track here.  Thanks!

**Comment by kinggath** [comment]
Added that as its own field and am using that for vendor production in the next patch (2.0.12).
