### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Freso** [kinggath/WorkshopFramework#37]
This mod is being listed as [open source](https://opensource.org/osd) on Nexus, but I don’t see what [open source license](https://opensource.org/licenses) is being used for it.

Is this declared somewhere that I’m missing?

**Comment by fourdragons** [comment]
By the very nature of "Open Source", one isn't required to declare an "official" licensing scheme.  While that is ideal, it's not required. The licensing details are expounded upon on the Nexus under the "Permissions and Credits" section of the "Description" page.  If those details match up with a specific "open source license", then there ya go. :)

**Comment by Freso** [comment]
> By the very nature of "Open Source", one isn't required to declare an "official" licensing scheme.

Please read [the definition of open source](https://opensource.org/osd). Without a license any released code is published under full, regular copyright protections and as such effectively proprietary, even if you are able to inspect the code (note that copyright is at its core about the *right to copy*, not about the *right to read*).

The "open" in open source is not just that you can inspect the code but is a very specific list of additional freedoms. (Several of these freedoms are not granted according to the "Permissions and credits" section on the Nexus mods page, meaning that barring other statements, this mod is **not** open source.)

**Comment by cadpnq** [comment]
I'm pretty sure this isn't the place to rehash this (eternal) argument. Like it or not, "open source" does not necessarily imply "conforms to the terms laid out in the OSD."

**Comment by kinggath** [comment]
I'm not interested in choosing a license, the reason to post this for Workshop Framework, is so you can see all of the code and make mods that take advantage of it. If you want to reuse bits you find in it, such as its patterns or certain functions, just be sure they don't conflict with the mod's functionality.

For example, don't keep the same namespace/filenames which would cause your versions to overwrite the release versions. Also, please maintain the header section that credits myself or others who have worked on each particular file.

**Comment by Freso** [comment]
In that case, please remove the statement that the mod is "open source" and state that the source code is available or public or some such instead.

**Comment by fourdragons** [comment]
Look, the alliance or whatever they call themselves lost the right to use “open source” exclusively. So nobody has to stop saying “open source”. Open source. Open source.

**Comment by Scrivener07** [comment]
In any case, explicit license or not, whatever you call it, thanks for making the source available here on github.
