### ISSUE TITLE
Option to limit settlers by number of beds

### ISSUE THREAD

**Issue by loc-n-lol** [kinggath/WorkshopFramework#40]
Simple enough.
Not all settlements are created equal, so having one hard limit for every settlement does not really work, and having to manually turn off the radio might be too late, not to mention you might be questing too far away to bother.
I know there's an unemplyed settlers limit as well, but again, it's probably too late by the time this one becomes relevant.

Limiting population to the number of beds means the player can easily control how much they want to grow each specific settlement, and also plan it ahead of time. 
A settlement with little space like hangman's alley will remain small unless the player deliberately wants to cram it full of bunk beds.

**Comment by skk50** [comment]
I do this (radio recruitment max = bed count) with my uncapped by CHR settler recruitment systems in Fallout 4-76, SKK Workshop Ownership Utilities & etc.

Works really well.

**Comment by kinggath** [comment]
Not sure how I missed this suggestion last year. This is a good and simple option to add. I'll put it on my shortlist for future implementation.

**Comment by kinggath** [comment]
Finally added this (this is what I get for taking on so many projects)! Will be Friday's update.
