### ISSUE TITLE
Possible Bug in WorkshopParentScript

### ISSUE THREAD

**Issue by niston** [kinggath/WorkshopFramework#67]
The code appears to be intended to increment WorkshopRatingPopulationUnassigned by one.
Instead, it looks like it is setting it to one. I think the author meant to use ModValue instead of SetValue?
	
; update workshop rating - increment unassigned actors total
theActor.SetValue(WorkshopRatings[WorkshopRatingPopulationUnassigned].resourceValue, 1)

**Comment by kinggath** [comment]
This is setting it on the actor itself, not on the settlement. So setting it to 1 is correct.
