### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by JRGypsy** [kinggath/WorkshopFramework#68]
How do you import a WSFW export file into a workshop? It says there are no available plans to import. I'm curious, why if WSFW exports a file, why can't it see the same file on Import? Speaking as a very experience (decades) programmer.......

**Comment by msalaba01** [comment]
You need to create a layout esp/esl with the web tool first.  Check out the videos in the link:
https://wiki.simsettlements2.com/en/contribute/building-contests#wsfw-converting-importing-exporting-and-layout-creation-webtool

**Comment by kinggath** [comment]
@JRGypsy Basically, the importing of text files is only possible with F4SE, the conversion method msalaba01 linked to ensures the imports can work without it, so they can be distributed on XBox.
