### ISSUE TITLE
Thread_PlaceObject uses incorrect AV WorkshopCurrentDraws when it should use WorkshopCurrentTriangles

### ISSUE THREAD

**Issue by littlej541** [kinggath/WorkshopFramework#69]
https://github.com/kinggath/WorkshopFramework/blob/39dcad7ba17e91be9000551acbf0e21b637e94a0/Scripts/Source/User/WorkshopFramework/ObjectRefs/Thread_PlaceObject.psc#L433

As title says, looks like the wrong actor value is used here.

**Comment by kinggath** [comment]
Good find. Fixed for the next build!
