### ISSUE TITLE
UtilityFunctions return value question

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#71]
https://github.com/kinggath/WorkshopFramework/blob/1c849379d3e4ed182ed303e854a564c9f66129bf/Scripts/Source/User/WorkshopFramework/Library/UtilityFunctions.psc#L1173-L1197
Should L1196 be `return ReturnIndexes`?

**Comment by kinggath** [comment]
Yep - that is definitely a typo! Will get fixed for next update.
