### ISSUE TITLE
Possible Auto Assign issue

### ISSUE THREAD

**Issue by msalaba01** [kinggath/WorkshopFramework#86]
In `NPCManager` `AddNewActorToWorkshop` it does not check for `(WSFW_Setting_AutoAssign_Beds.GetValueInt() == 1) as Bool` before calling `TryToAssignBeds`
https://github.com/kinggath/WorkshopFramework/blob/affc4fa356292e356cb518784f8e31ad331511fd/Scripts/Source/User/WorkshopFramework/NPCManager.psc#L690-L693
It should look more like:
```
if(iNewWorkshopID == iCurrentWorkshopID && (WSFW_Setting_AutoAssign_Beds.GetValueInt() == 1) as Bool)
	WorkshopParent.TryToAssignBeds(akWorkshopRef)
endif
```
Wim95 reported this here:
https://simsettlements.com/site/index.php?threads/auto-assignment-still-happening-after-disabling-in-mcm.17775/post-127801

**Comment by kinggath** [comment]
Fixed for next build.
