### ISSUE TITLE
Only surplus water is deposited in workshop when not in settlement

### ISSUE THREAD

**Issue by evilzer** [kinggath/WorkshopFramework#93]
**Steps to reproduce:**
1. Started new game and took Sanctuary, got food and water production going.
2. Waited 24 hours in settlement to make sure surplus food/water is added into workshop.
3. Ran to fireplace area outside Concord where the radiant spawn marker is located, waited 24 hours.
4. Ran back, there is only water in workshop settlement.

Without WSFW. both food and water is added into workshop. Tested with only WSFW ( and F4SE) active.

**Comment by kinggath** [comment]
Either we incidentally fixed this since your post, or there's a conflict at work here. 

I just tested in Sanctuary and am definitely seeing Food and Water produced.

![image](https://user-images.githubusercontent.com/32745886/162836064-0e6caef0-20c9-4713-977c-2a8d0e13de6b.png)
